// examples/earthsdk3-vite/src/components/Container.vue
<template>
  <div class="box">

    <div class="btn-box">
      <botton @click="switchViewer('cesium')">切换为Cesium</botton>
      <botton @click="switchViewer('ue')">切换为UE</botton>
      <botton @click="switchViewer('openlayers')">切换为Openlayers</botton>
    </div>

    <!-- 视口容器 -->
    <div class="container" ref="container"></div>

  </div>

</template>

<script setup lang="ts">
import { nextTick, ref } from 'vue';
import { getobjm } from '../scripts/getobjm';
import { ESViewer } from 'earthsdk3';

const objm = getobjm();
const container = ref<HTMLDivElement>();

nextTick(() => {
  if (!container.value) return;
  //创建视口
  const viewer = objm.createCesiumViewer(container.value);
  console.log(viewer);
})


//切换视口
const switchViewer = (type: string) => {
  if (!container.value) return;
  if (type === 'cesium') {

    const option = {
      container: container.value,
      type: 'ESCesiumViewer'
    };

    //切换cesium视口
    objm.switchViewer(option);

  } else if (type === 'ue') {

    const option = {
      container: container.value,
      type: 'ESUeViewer',
      options: {
        uri: 'http://localhost:9007/',
        app: 'earthsdk3'
      }
    };
    //切换ue视口
    objm.switchViewer(option);


  } else if (type === 'openlayers') {

    const option = {
      container: container.value,
      type: 'ESOlViewer'
    };
    //切换ol视口
    objm.switchViewer(option);

  }
}

</script>
<style scoped>
.box {
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: flex-start;
  align-items: center;
  position: relative;
}

.btn-box {
  height: 50px;
  position: absolute;
  left: 0px;
  top: 0px;
  display: flex;
  justify-content: flex-start;
  align-items: center;
  z-index: 1;
}

.container {
  width: 100%;
  height: 100%;
  position: relative;
}

botton {
  padding: 0 10px;
  height: 30px;
  margin: 10px;
  background-color: #01fa7d8c;
  border: 1px solid #01fa7d8c;
  border-radius: 5px;
  cursor: pointer;
  color: #fff;
  font-size: 14px;
  text-align: center;
  line-height: 30px;
}
</style>

// examples/earthsdk3-react-vite/src/Container.tsx
import type { ESObjectsManager, ESViewer, ESVOption } from 'earthsdk3';
import { useEffect, useRef } from 'react';
import './style.css';

export default function Container({ objm }: { objm: ESObjectsManager }) {
    const containerRef = useRef<HTMLDivElement | null>(null);

    // 切换引擎
    const switchViewer = (type: 'cesium' | 'ue') => {
        if (!containerRef.current) return;
        let option: ESVOption = {
            type: 'ESCesiumViewer',
            container: containerRef.current
        };
        if (type === 'ue') {
            option = {
                type: 'ESUeViewer',
                container: containerRef.current,
                options: {
                    uri: 'http://localhost:9007/',
                    app: 'earthsdk3'
                }
            };
        }
        objm.switchViewer(option);
    };


    // 初始化Cesium
    let viewer: ESViewer | null = null;
    useEffect(() => {
        if (viewer || !containerRef.current) return;
        viewer = objm.createCesiumViewer(containerRef.current);
        console.log('viewer', viewer);
    }, []);

    return (
        <div className="box">
            <div className="btn-box">
                <button className="btn" onClick={() => switchViewer('cesium')}>切换Cesium</button>
                <button className="btn" onClick={() => switchViewer('ue')}>切换UE</button>
            </div>
            <div className="container" ref={containerRef}></div>
        </div>
    );
}
